# Generated by Django 3.1.1 on 2020-12-19 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailAddress', models.CharField(max_length=200)),
                ('describeAddress', models.CharField(max_length=200)),
                ('roomType', models.CharField(choices=[('phòng trọ', 'phòng trọ'), ('chung cư mini', 'chung cư mini'), ('nhà nguyên căn', 'nhà nguyên căn'), ('chung cư nguyên căn', 'chung cư nguyên căn')], max_length=100)),
                ('numberOfRoom', models.PositiveIntegerField()),
                ('numberOfRented', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField()),
                ('rent_time', models.CharField(choices=[('tháng', 'tháng'), ('quý', 'quý'), ('năm', 'năm')], max_length=10)),
                ('square', models.PositiveIntegerField(default=0)),
                ('withOwner', models.BooleanField()),
                ('bathroomType', models.CharField(choices=[('khép kín', 'khép kín'), ('chung', 'chung')], max_length=20)),
                ('heater', models.BooleanField()),
                ('kitchen', models.CharField(choices=[('khu bếp riêng', 'khu bếp riêng'), ('khu bếp chung', 'khu bếp chung'), ('không nấu ăn', 'không nấu ăn')], max_length=50)),
                ('airconditioner', models.BooleanField()),
                ('balcony', models.BooleanField()),
                ('water_price', models.PositiveIntegerField()),
                ('electricity_price', models.PositiveIntegerField()),
                ('other', models.CharField(blank=True, max_length=200, null=True)),
                ('images', models.TextField(blank=True)),
                ('expiredDate', models.DateTimeField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('hostName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostName', to='Account.host')),
            ],
        ),
    ]
