# Generated by Django 3.1.1 on 2020-12-07 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailAddress', models.CharField(max_length=200)),
                ('describeAddress', models.CharField(max_length=200)),
                ('roomType', models.CharField(choices=[('pt', 'phòng trọ'), ('cc', 'chung cư mini'), ('n', 'nhà nguyên căn'), ('ccnc', 'chung cư nguyên căn')], max_length=100)),
                ('numberOfRoom', models.PositiveIntegerField()),
                ('numberOfRented', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField()),
                ('withOwner', models.BooleanField()),
                ('bathroomType', models.CharField(choices=[('kk', 'khép kín'), ('c', 'chung')], max_length=20)),
                ('kitchen', models.CharField(choices=[('r', 'khu bếp riêng'), ('c', 'khu bếp chung'), ('k', 'không nấu ăn')], max_length=50)),
                ('airconditioner', models.BooleanField()),
                ('balcony', models.BooleanField()),
                ('utility', models.PositiveIntegerField()),
                ('other', models.CharField(blank=True, max_length=200, null=True)),
                ('images', models.ImageField(blank=True, upload_to='')),
                ('hostName', models.CharField(max_length=50)),
                ('hostPhoneNumber', models.CharField(max_length=50)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_of_this_post', to='Account.host')),
            ],
        ),
    ]
