# Generated by Django 3.1.1 on 2020-12-19 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hostPhoneNumber',
        ),
        migrations.AlterField(
            model_name='post',
            name='hostName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostName', to='Account.host'),
        ),
    ]
