# Generated by Django 3.1.1 on 2020-12-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
