# Generated by Django 3.1.1 on 2020-12-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_post_total_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
