# Generated by Django 3.1.1 on 2020-12-19 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Post', '0001_initial'),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('is_confirmed', models.BooleanField()),
                ('date_report', models.DateTimeField(auto_now_add=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_report', to='Post.post')),
                ('renter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_report', to='Account.renter')),
            ],
        ),
    ]
