# Generated by Django 3.1.1 on 2020-12-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Views', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='views',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
